### ISSUE TITLE
Update "GlobalEnums" doesn't turn the Dirty property

### ISSUE THREAD

**Issue by lidor-b** [michalcohen/ConfigurationManager#13]
When i added values to the GlobalEnums and then close the window (without saving), the dialog box of saving the changes doesn't shoes up so which means the Dirty propery is still false and the changed values are lost.

**Comment by michalcohen** [comment]
The DialogBox always appears when I change something in EnumsView, but from time to time, the json file itself doesn't change. It is very strange. If you find out consistent reason for this behavior, write it here :)

**Comment by lidor-b** [comment]
Now i tried to edit a global enum and the changes have not been detected. However, when i delete a global enum it does works properly.

**Comment by michalcohen** [comment]
I think it was fixed. Can you please try again and update me?
